### ISSUE TITLE
Download Status

### ISSUE THREAD

**Issue by nomad5am** [Tenpi/soundcloud-extension#1]
First of all, you're legend! This extension is much needed. Thank you!
Anyway, it's really important to somehow see if downloads are in progress (without the developer console) cause otherwise clicking a few times on Download will start the download dozens of times.

**Comment by Tenpi** [comment]
Sounds good. I will try to implement this by replacing the button with a spinning icon while it's downloading. Worth noting that if you download the same song it will overwrite the last download, so you don't have to worry about downloading dozens of duplicates.

**Comment by Tenpi** [comment]
I implemented the loading spinner in v0.1.4, commit e29a3463205bdc48afc3e7f57008d7cb2473820e. Let me know if you have any additional suggestions.
