### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by JacksonSteel** [Tenpi/soundcloud-extension#3]
append the download button to every track on Stream

**Comment by Tenpi** [comment]
Ok, I added this in `v0.1.7`. It takes a couple weeks for it to get reviewed on Chrome/Firefox, but I published the zip file on the releases tab if you want to use it now: https://github.com/Tenpi/soundcloud-extension/releases

**Comment by Tenpi** [comment]
Btw, it already got approved on Chrome/Firefox. I haven't tested it a lot so let me know if you experience bugs.
