### ISSUE TITLE
It is not working

### ISSUE THREAD

**Issue by lynzh** [Tenpi/soundcloud-extension#5]
~~It does not seem to be working, when you click download there appears a loading icon and then it loads forever and nothing happens. I am not sure how to debug it, any suggestions Tenpi?~~

OK, After refreshing to another page it seems to work perfectly.

**Comment by Tenpi** [comment]
I can't help you with a vague "doesn't work" request. Preferably it should work without needing to refresh the page so I will still consider it a bug. Let me know what track(s) you downloaded or what actions you took so that I am able to reproduce it.
