### ISSUE TITLE
higher resolution on cover art?

### ISSUE THREAD

**Issue by kahunya** [Tenpi/soundcloud-extension#6]
lo-res cover art poppin up in my musicbee, pretty sure sc stores images 500x500

![c9d122b1f265902caab8d498598d315a](https://user-images.githubusercontent.com/48972970/113939805-49514300-97b1-11eb-95d7-c3ba03964df7.png)

**Comment by Tenpi** [comment]
Hi, I increased the resolution of the cover art in `v0.2.4`. If you're interested I could also add an option to download the cover art images.

**Comment by kahunya** [comment]
thank you, and yeah that would be nice

**Comment by Tenpi** [comment]
> thank you, and yeah that would be nice

Ok, added it in `v0.2.5`. You can tell the difference because the extension will change to a pink color.
Closing this because its resolved.
