### ISSUE TITLE
Download animation spinning but no download button

### ISSUE THREAD

**Issue by MyKhan** [Tenpi/soundcloud-extension#7]
In some cases, when you click the button, the animation simply runs but the download link does not appear. I saw there were other cases open that had a similar issue and that it was due to some characters and that you had fixed it. Maybe this is a similar issue since the artist has a weird character in the name: https://soundcloud.com/ayamari-official/are-you-afraid-of-the-future
But then this one doesn't seem to have that sort of issue and still the download button never comes: https://soundcloud.com/charleenguyen/neverland

By the way, just wanted to say thanks for the great piece of software! 👍

**Comment by Tenpi** [comment]
Hello, I downloaded both those tracks without any problems. I would double check that you're on the latest version (v0.2.6). Until I can reproduce the error there's not much I can do.

![dlexample](https://user-images.githubusercontent.com/37512637/116594350-1a317b80-a8f0-11eb-882c-9da1354bd4e1.png)
