### ISSUE TITLE
Downloading .mp3.part

### ISSUE THREAD

**Issue by coggi22c** [Tenpi/soundcloud-extension#8]
Trying to download any song from https://soundcloud.com/marianas-trench-official gives .mp3.part files.  This is the only artist I've downloaded from that has caused this issue.

**Comment by Tenpi** [comment]
Maybe you have incorrect MIME settings set in the Registry? For example, if the MIME type "audio/mp3" has the extension set to something other than ".mp3" Chrome will always download it as that other extension. The same also applies if you are downloading the cover photos but it downloads as an extension other than .jpg.  

See this guide:
https://www.winhelponline.com/blog/fix-mp3-saved-with-incorrect-extension-when-downloaded/

**Comment by coggi22c** [comment]
According to https://discussions.apple.com/thread/1790956, the problem comes from the download never finishing.  Changing the extension to .mp3 doesn't work, so the download really is unfinished.  I've tried downloading from a bunch of other random artists and they all work fine, and I've tried downloading from marianas-trench-official a few times every day and I still get the broken download.

**Comment by Tenpi** [comment]
> According to https://discussions.apple.com/thread/1790956, the problem comes from the download never finishing. Changing the extension to .mp3 doesn't work, so the download really is unfinished. I've tried downloading from a bunch of other random artists and they all work fine, and I've tried downloading from marianas-trench-official a few times every day and I still get the broken download.

Which browser are you using? It works perfectly fine on Chrome, however I just verified that on Firefox it never downloads, no errors or anything. I never get a download with a .mp3.part extension though, it just silently fails.

The tracks from this artist are not direct mp3 streams, instead they are all m3u playlists. I use a third party dependency to handle m3u files, so I will forward this issue over to them.

**Comment by coggi22c** [comment]
I'm on Firefox, the download is never confirmed in the browser but it shows up in my downloads folder.  The broken file actually being kept is probably a Mac + Firefox thing.  I was able to get the download from Chrome though, thanks for the help!

**Comment by Tenpi** [comment]
I fixed this in `v0.2.8`.
