### ISSUE TITLE
Working? Hung-up?

### ISSUE THREAD

**Issue by Austinhagele** [Tenpi/soundcloud-extension#9]
First, I love the extension you are awesome. I don't know if this is a feature request or a bug. My issue is downloading large playlists such as one I made (https://soundcloud.com/austinph/sets/singles) I click download and it spins, I know it would take some time, but I let it work for 3 hours plus, while I didn't use the computer and it's still spinning. so I don't know if it's still chugging along because it's a large list or if it got hung up along the way, so maybe a progress bar so I can see that it's still working.

**Comment by Tenpi** [comment]
I'll look into it later, but it sounds either like a bug or a purposeful block by the browser (because it's probably not a good idea to let an extension initiate hundreds of downloads).

**Comment by Tenpi** [comment]
Fixed as of `v0.2.9`. Problematic track is this one:
https://soundcloud.com/armadarecordbox/di-rect-invincible-ducked-ape-remix
Which is not available in the United States.
